name: Test PyPi Publish
on:
  push:
    tags:
      - v*
jobs:
  # test-env:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Retreive test pypi API token
  #       # env:
  #       #   TEST_PYPI_API_TOKEN: ${{secrets.TEST_PYPI_API_TOKEN}}
  #       run: |
  #         echo "$github.ref"
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      # tries to get cached dependncies (invalidated on lockfile changing)
      - name: load cached venv
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      
      - name: install dependencies
        run: poetry install --no-interaction --no-root
      
      - name: build and publish to TestPyPI
        env:
          TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi $TEST_PYPI_API_TOKEN
          poetry publish --build -r testpypi
