name: Test PyPi Publish
on:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  # test-env:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Retreive test pypi API token
  #       env:
  #         TEST_PYPI_API_TOKEN: ${{secrets.TEST_PYPI_API_TOKEN}}
  #       run: |
  #         echo "$TEST_PYPI_API_TOKEN"
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: run vast cli 
        run: python vast.py
